---
- name: Check if nvidia-smi is available and working
  command: nvidia-smi
  ignore_errors: yes
  register: nvidia_smi_check1

# only remove if nvidia-smi is not available
- name: Cleanup existing NVIDIA drivers
  shell: "apt autoremove nvidia* --purge -y"
  when: nvidia_smi_check1.rc != 0 
  ignore_errors: yes

- name: Reboot the system
  when: nvidia_smi_check1.rc != 0 
  reboot:

- name: Wait for system to come back online after reboot
  when: nvidia_smi_check1.rc != 0 
  wait_for_connection:
    delay: 30
    timeout: 300

- name: Update package lists
  when: nvidia_smi_check1.rc != 0 
  apt:
    update_cache: yes
    upgrade: yes

- name: Install NTP
  apt:
    name: ntp
    state: present

- name: List GPGPU drivers
  when: nvidia_smi_check1.rc != 0 
  command: ubuntu-drivers list --gpgpu
  register: gpu_drivers_list

- name: Output GPGPU drivers list
  when: nvidia_smi_check1.rc != 0 
  debug:
    msg: "{{ gpu_drivers_list.stdout }}"

- name: Install NVIDIA driver
  when: nvidia_smi_check1.rc != 0 
  apt:
    name:
      - nvidia-driver-535
      # - nvidia-dkms-535
    state: present
    update_cache: yes
  register: nvidia_driver_installation

- name: Output NVIDIA driver installation result
  when: nvidia_smi_check1.rc != 0 
  debug:
    var: nvidia_driver_installation

- name: Reboot the system
  when: nvidia_smi_check1.rc != 0 
  reboot:

- name: Wait for system to come back online after reboot
  when: nvidia_smi_check1.rc != 0 
  wait_for_connection:
    delay: 30
    timeout: 300

- name: Check NVIDIA-SMI
  command: nvidia-smi
  register: nvidia_smi_output
  failed_when: nvidia_smi_output.rc != 0

- name: Extract Driver version
  set_fact:
    driver_version: "{{ nvidia_smi_output.stdout | regex_search('Driver Version:\\s*(\\S+)', '\\1') | first }}"

- name: Extract GPU name
  set_fact:
    gpu_name: "{{ nvidia_smi_output.stdout_lines[8] | regex_search('\\|\\s*([^\\|]+)\\s*\\|', '\\1') | first | trim }}"

# - name: Output NVIDIA-SMI result
#   debug:
#     var: nvidia_smi_output.stdout

- name: Output GPU Name and Driver Version
  debug:
    msg: "GPU: {{ gpu_name }}, NVIDIA Driver Version: {{ driver_version }}"

- name: Install nvtop
  apt:
    name: nvtop
    state: present
    update_cache: yes
