steps:
  # Step 1: Clone the main repository including submodules
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--recurse-submodules', 'https://github.com/NeuralEnergy/AiLibrary.git', '.']
    dir: 'workspace'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ne-ailib', '.']
    dir: 'workspace'

  # Step 3: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ne-ailib']
    dir: 'workspace'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'ne-ailib-service'  # Cloud Run service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/ne-ailib' # our above defined image
    - '--region'
    - '$LOCATION'  # desired region
    - '--set-env-vars' # each env var must be defined in the GCP trigger Substitution variables
    - > # use YAML block scalar for the env vars to avoid quoting issues
      NEAIL_TELEGRAM_TOKEN=$_NEAIL_TELEGRAM_TOKEN, 
      NEAIL_MOTION_TOKEN=$_NEAIL_MOTION_TOKEN,
      NEAIL_GPT_KEY=$_NEAIL_GPT_KEY,
      NEAIL_HF_TOKEN=$_NEAIL_HF_TOKEN  # Split environment variables
    - '--allow-unauthenticated' # free for all API
    - '--port' # the container port not the service port
    - '5002'
    - '--memory'
    - '2Gi'     # increase memory limit from basic of 512MB
    - '--cpu'
    - '2'       # increase CPU limit from basic of 1
    - '--min-instances'
    - '1'    # set the minimum number of instances to 1 to make sure the service is always on
    - '--max-instances'
    - '1'    # set the maximum number of instances to 1 to accomodate singleton behaviour
    
    # Additional Cloud Run configurations can be added here

images:
  - 'gcr.io/$PROJECT_ID/ne-ailib'
