steps:
  # Step 1: Clone the main repository including submodules
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--recurse-submodules', 'https://github.com/NeuralEnergy/AiLibrary.git', '.']
    dir: 'workspace'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ne-ailib', '.']
    dir: 'workspace'

  # Step 3: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ne-ailib']
    dir: 'workspace'

steps:
  # ... [previous steps for cloning, building, and pushing the image]

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'ne-ailib-service'  # Replace with your Cloud Run service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/ne-ailib'
    - '--region'
    - 'us-central1-a'  # Replace with your desired region
    - '--allow-unauthenticated'
    # Additional Cloud Run configurations can be added here

images:
  - 'gcr.io/$PROJECT_ID/ne-ailib'
