steps:
  # Step 1: Clone the main repository including submodules
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--recurse-submodules', 'https://github.com/NeuralEnergy/AiLibrary.git', '.']
    dir: 'workspace'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ne-ailib', '.']
    dir: 'workspace'

  # Step 3: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ne-ailib']
    dir: 'workspace'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'ne-ailib-service'  # Cloud Run service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/ne-ailib'
    - '--region'
    - '$LOCATION'  # desired region
    - '--set-env-vars'
    - >
      NEAIL_TELEGRAM_TOKEN=$_NEAIL_TELEGRAM_TOKEN,
      NEAIL_MOTION_TOKEN=$_NEAIL_MOTION_TOKEN,
      NEAIL_GPT_KEY=$_NEAIL_GPT_KEY,
      NEAIL_HF_TOKEN=$_NEAIL_HF_TOKEN  # Split environment variables
    - '--allow-unauthenticated'
    - '--port'
    - '5002'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'    
    # Additional Cloud Run configurations can be added here

images:
  - 'gcr.io/$PROJECT_ID/ne-ailib'
