FROM aidamian/base_llm_env:latest

WORKDIR /workspaces

ENV TZ Europe/Bucharest

ENV AID_APP_DOCKER Yes
ENV SHOW_PACKS Yes
ENV FORCE_CPU No
ENV AID_APP_ID BaseAidApp

#ENV PYTHONPATH .
EXPOSE 5001-5015/tcp