---
- name: Check if NVIDIA-SMI is available and working
  command: nvidia-smi
  ignore_errors: yes
  register: nvidia_smi_check1
  # This task checks if NVIDIA's System Management Interface (nvidia-smi) is available.
  # It is a quick way to verify if NVIDIA drivers are properly installed.

- name: Cleanup existing NVIDIA drivers
  shell: "apt autoremove nvidia* --purge -y"
  when: nvidia_smi_check1.rc != 0
  ignore_errors: yes
  # Runs only if initial nvidia-smi check failed.
  # This task removes any existing NVIDIA drivers only if nvidia-smi is not found.
  # It ensures that the system is cleaned up before installing new drivers.

- name: Reboot the system
  when: nvidia_smi_check1.rc != 0
  reboot:
  # Runs only if initial nvidia-smi check failed.
  # A reboot is required after removing the NVIDIA drivers to ensure that changes take effect.
  # The system will only reboot if the NVIDIA drivers were removed.

- name: Wait for system to come back online after reboot
  when: nvidia_smi_check1.rc != 0
  wait_for_connection:
    delay: 30
    timeout: 300
  # Runs only if initial nvidia-smi check failed.
  # This task waits for the system to come back online after a reboot.
  # It ensures that subsequent tasks do not run before the system is ready.

- name: Update package lists
  when: nvidia_smi_check1.rc != 0
  apt:
    update_cache: yes
    upgrade: yes
  # Runs only if initial nvidia-smi check failed.
  # Update the package lists and upgrade packages only if NVIDIA drivers were not found.
  # This is essential to ensure the latest packages and dependencies are installed.

- name: Install NTP
  apt:
    name: ntp
    state: present
  # Installs Network Time Protocol (NTP) to keep the system time synchronized.
  # This is important for many networked services and logging.

- name: List GPGPU drivers
  when: nvidia_smi_check1.rc != 0
  command: ubuntu-drivers list --gpgpu
  register: gpu_drivers_list
  # Runs only if initial nvidia-smi check failed.
  # Lists the available GPGPU drivers, a helpful step to check compatible drivers.

- name: Output GPGPU drivers list
  when: nvidia_smi_check1.rc != 0
  debug:
    msg: "{{ gpu_drivers_list.stdout }}"
  # Runs only if initial nvidia-smi check failed.
  # Outputs the list of available GPGPU drivers for informational purposes.

- name: Install NVIDIA driver
  when: nvidia_smi_check1.rc != 0
  apt:
    name:
      - nvidia-driver-535
    state: present
    update_cache: yes
  register: nvidia_driver_installation
  # Runs only if initial nvidia-smi check failed.
  # Installs the specified NVIDIA driver. The version should be updated as needed.
  # This task is executed only if the initial check for NVIDIA drivers failed.

- name: Output NVIDIA driver installation result
  when: nvidia_smi_check1.rc != 0
  debug:
    var: nvidia_driver_installation
  # Runs only if initial nvidia-smi check failed.
  # Outputs the result of the NVIDIA driver installation for verification.

- name: Reboot the system
  when: nvidia_smi_check1.rc != 0
  reboot:
  # Runs only if initial nvidia-smi check failed.
  # Rebooting again to ensure the new NVIDIA drivers are properly loaded.

- name: Wait for system to come back online after reboot
  when: nvidia_smi_check1.rc != 0
  wait_for_connection:
    delay: 30
    timeout: 300
  # Runs only if initial nvidia-smi check failed.
  # Waits for the system to be ready after the second reboot.

- name: Check NVIDIA-SMI
  command: nvidia-smi
  register: nvidia_smi_output
  failed_when: nvidia_smi_output.rc != 0
  # Verifies that NVIDIA-SMI is functional after driver installation.
  # This is a second check to ensure that the NVIDIA drivers were properly installed.

- name: Extract Driver version
  set_fact:
    driver_version: "{{ nvidia_smi_output.stdout | regex_search('Driver Version:\\s*(\\S+)', '\\1') | first }}"
  # Extracts the NVIDIA driver version from the nvidia-smi output.

- name: Extract GPU name
  set_fact:
    gpu_name: "{{ nvidia_smi_output.stdout_lines[8] | regex_search('\\|\\s*([^\\|]+)\\s*\\|', '\\1') | first | trim }}"
  # Extracts the GPU name from the nvidia-smi output.

- name: Output GPU Name and Driver Version
  debug:
    msg: "GPU: {{ gpu_name }}, NVIDIA Driver Version: {{ driver_version }}"
  # Outputs the GPU name and driver version for confirmation.

- name: Install nvtop
  apt:
    name: nvtop
    state: present
    update_cache: yes
  # Installs nvtop, a tool for monitoring NVIDIA GPUs, which can be useful for diagnostics and performance monitoring.
