---
# - name: Deploy on GPU Workers
#   hosts: gpu_workers
#   become: true
#   gather_facts: true
#   roles:
#     - s01_gpu
#     - s02_docker
#     - s03_nvidia
#     - s09_dkr_gpu_test

# - name: Deploy service on GPU Worker #1
#   hosts: ne1
#   become: true
#   gather_facts: true
#   vars:
#     llm_api_port: 5080
#   roles:
#     - s04_deploy

# - name: Deploy on NON-GPU Workers
#   hosts: non_gpu_workers
#   become: true
#   gather_facts: true
#   roles:
#     - s02_docker

# - name: Deploy docker on Kubernetes master
#   hosts: kube_masters
#   become: true
#   gather_facts: true
#   roles:
#     - s02_docker

- name: Deploy Kubernetes using unified role
  hosts: all
  become: true
  gather_facts: true
  roles:
    - s10_k8s

# - name: Run final test on master
#   hosts: kube_masters
#   become: true
#   gather_facts: true
#   roles:
#     - s15_k8s_test